
package msra_rankbase02.spacewalkv4;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WebService", targetNamespace = "http://msra-rankbase02/spacewalkv4/", wsdlLocation = "http://msra-rankbase02/spacewalkv4/WebService.asmx?WSDL")
public class WebService
    extends Service
{

    private final static URL WEBSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(msra_rankbase02.spacewalkv4.WebService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = msra_rankbase02.spacewalkv4.WebService.class.getResource(".");
            url = new URL(baseUrl, "http://msra-rankbase02/spacewalkv4/WebService.asmx?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://msra-rankbase02/spacewalkv4/WebService.asmx?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WEBSERVICE_WSDL_LOCATION = url;
    }

    public WebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebService() {
        super(WEBSERVICE_WSDL_LOCATION, new QName("http://msra-rankbase02/spacewalkv4/", "WebService"));
    }

    /**
     * 
     * @return
     *     returns WebServiceSoap
     */
    @WebEndpoint(name = "WebServiceSoap")
    public WebServiceSoap getWebServiceSoap() {
        return super.getPort(new QName("http://msra-rankbase02/spacewalkv4/", "WebServiceSoap"), WebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceSoap
     */
    @WebEndpoint(name = "WebServiceSoap")
    public WebServiceSoap getWebServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://msra-rankbase02/spacewalkv4/", "WebServiceSoap"), WebServiceSoap.class, features);
    }

}
